import Link from "next/link";
import "./globals.css";


export const metadata = {
  title:{
    default: "Burger King",
    template:"%s | King"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
         <nav className="flex h-[10vh] justify-between bg-red-800 text-white px-10 items-center">
            <h1>Burger King</h1>
            <ul className="flex gap-10">
              <li><Link href="/">Home</Link></li>
              <li><Link href="category">Category</Link></li>
              <li><Link href="region">Region</Link></li>
              <li><Link href="name">Name</Link></li>
            </ul>
         </nav>
        </header>
        {children}
        <footer className="bg-orange-900 text-white flex justify-center items-center h-[10vh]">
          <p>All rights reserved 2025</p>
        </footer>
      </body>
    </html>
  );
}
